[metadata]
description_file = README.md
name = heceramics
version = attr: src.VERSION
description = Program to predict carbon vacancy formation energy in high entropy carbides
long_description = file: README.rst, LICENSE.rst
keywords = heceramics
license = MIT
classifiers =
    Programming Language :: Python :: 3.5
